name: scikitbuild
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cmake
  - gxx
  - scikit-build
  - pybind11
  - cython
  - tbb-devel
  - toml # for python -m build
  - zipp # for python -m build
